### ISSUE TITLE
Both skins look the same

### ISSUE THREAD

**Issue by azuraji** [glassleo/Masque_Newsom#1]
I'm not sure if has to do with the major updates to Masque, but when it comes the Newsom skins, they both now look the same.

Switching between Newsom and Newsom Outline, I can see virtually no difference. I'm trying this out on the buff frame using [Masque Skinner: Blizz Buffs](https://github.com/ascott18/Masque-Skinner-Blizz-Buffs).

![image](https://user-images.githubusercontent.com/72912613/202830271-cf0ed598-099a-4bc4-a524-2937135b4b15.png)

**Comment by glassleo** [comment]
For stuff like action buttons they look identical yes. The difference between them is how debuff/item quality borders look. Original doesn't have one and Outline has an outline border around the icon, if specified by the addon.
